server:
  port: 8282
  ssl:
    bundle: web-server-bundle

# ===================================================================
# Spring Configuration
# ===================================================================
spring:
  application:
    name: auth-server

  main:
    banner-mode: off

  output:
    ansi:
      enabled: always

  # --- SSL Bundles ---
  ssl:
    bundle:
      jks:
        web-server-bundle: # user-defined name
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12

        client-trust-bundle: # user-defined name
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
          truststore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12

  # --- Database Configuration ---
  datasource:
    url: jdbc:mysql://localhost:3806/bookommerce-auth-server-dev-db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  session:
    jdbc:
      initialize-schema: always

  # --- Redis Configuration ---
  data:
    redis:
      host: localhost
      port: 6379

# ===================================================================
# Logging Configuration
# ===================================================================
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        security.oauth2.client.web: DEBUG
        security.web.authentication: DEBUG
        # session:
        #   jdbc: DEBUG
        # jdbc:
        #   core:
        #     JdbcTemplate: DEBUG
        #     StatementCreatorUtils: TRACE

  file:
    name: ./logs/auth-server.log

  logback:
    rollingpolicy:
      max-file-size: 1024MB
      clean-history-on-start: true
      max-history: 0

  pattern:
    console: "%d{HH:mm:ss.SSS} | %clr(%level) | %clr(%logger{0}){green}: %msg%n"
    file: "%d{HH:mm:ss.SSS} | %level | %logger{0}: %msg%n"

# ===================================================================
# Messaging / Stream Configuration
# ===================================================================
stream:
  key: user-events
  group: user-group

# ===================================================================
# Bookommerce URLs
# ===================================================================
bookommerce:
  urls:
    web-base-url: https://app.bookommerce.com:8080
    api-gateway-base-url: https://bff.bookommerce.com:8181
    auth-server-base-url: https://auth.bookommerce.com:8282

