server:
  port: 8282
  ssl:
    bundle: web-server-bundle

spring:
  ssl:
    bundle:
      jks:
        web-server-bundle:
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
        client-trust-bundle:
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
          truststore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3806/bookommerce-auth-server-dev-db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        session:
          jdbc: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
  file:
    name: logs/auth-server.log
  logback:
    rollingpolicy:
      max-file-size: 1024MB

stream:
  key: user-events
  group: user-group