spring:
  application:
    name: auth-server
  cloud:
    config:
      tls:
        enabled: true
        trust-store: classpath:auth-server-truststore.p12
        trust-store-password: ${AUTH_SERVER_TRUSTSTORE_PASSWORD:password}
  config:
    import: "optional:configserver:https://config.bookommerce.com:8888"
