server:
  port: 8383
  ssl:
    bundle: web-server-bundle

spring:
  ssl:
    bundle:
      jks:
        web-server-bundle:
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
        client-trust-bundle:
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
          truststore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
  application:
    name: Bookommerce
  datasource:
    url: jdbc:mysql://localhost:3806/bookommerce_dev_db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
        # data:
        #   redis: DEBUG
    #     redis:
    #       connection: DEBUG
    # io:
    #   lettuce:
    #     core: DEBUG
  file:
    name: logs/resource-server.log
    max-size: 1024MB

upload:
  image:
    book: C:\Users\PC\OneDrive\Desktop\bookommerce\resource-server\upload\image\book\

stream:
  key: user-events
  group: user-group
    
