server:
  port: 8383
  ssl:
    bundle: web-server-bundle

spring:
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  ssl:
    bundle:
      jks:
        web-server-bundle: #user-defined name
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
        client-trust-bundle: #user-defined name
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
          truststore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
  application:
    name: Bookommerce
  datasource:
    url: jdbc:mysql://localhost:3806/bookommerce_dev_db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    name: ./logs/resource-server.log
    max-size: 1024MB
    max-history: 0
    clean-history-on-start: true
  pattern:
    console: "%d{HH:mm:ss.SSS} | %clr(%level) | %clr(%logger{0}){green}: %msg%n"
    file: "%d{HH:mm:ss.SSS} | %level | %logger{0}: %msg%n"

upload:
  image:
    book: C:\Users\PC\OneDrive\Desktop\bookommerce\resource-server\upload\image\book\
    avatar: C:\Users\PC\OneDrive\Desktop\bookommerce\resource-server\upload\image\avatar\
    avatar.default: C:\Users\PC\OneDrive\Desktop\bookommerce\resource-server\upload\image\avatar\default\

stream:
  key: user-events
  group: user-group
    
