server:
  port: 8181
  ssl:
    bundle: web-server-bundle

spring:
  ssl:
    bundle:
      jks:
        web-server-bundle:
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
        client-trust-bundle:
          key:
            alias: bookommerce_ssl
          keystore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
          truststore:
            location: classpath:bookommerce-ssl.p12
            password: 123456
            type: PKCS12
  application:
    name: be-for-fe
  datasource:
    url: jdbc:mysql://localhost:3806/bookommerce-bff-dev-db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

logging:
  file:
    name: logs/bff.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        tool:
          schema: DEBUG
      springframework:
        security: DEBUG
        session:
          jdbc: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE