spring:
  application:
    name: be-for-fe
  cloud:
    config:
      tls:
        enabled: true
        trust-store: classpath:bff-truststore.p12
        trust-store-password: ${BFF_TRUSTSTORE_PASSWORD:password}
  config:
    import: "optional:configserver:https://config.bookommerce.com:8888"
