server:
  port: 8282
  ssl:
    bundle: auth-server-ssl
spring:
  ssl:
    bundle:
      jks:
        auth-server-ssl:
          keystore:
            location: classpath:auth-server-keystore.p12
            password: ${AUTH_SERVER_KEYSTORE_PASSWORD:password}
          truststore:
            location: classpath:auth-server-truststore.p12
            password: ${AUTH_SERVER_TRUSTSTORE_PASSWORD:password}
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3806/bookommerce-auth-server-dev-db
    username: root
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    jdbc:
      initialize-schema: always
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        '[security.oauth2.client.web]': DEBUG
        '[security.web.authentication]': DEBUG
  file:
    name: ./logs/auth-server.log
  logback:
    rollingpolicy:
      max-file-size: 1024MB
      clean-history-on-start: true
      max-history: 0
  pattern:
    console: "%d{HH:mm:ss.SSS} | %clr(%level) | %clr(%logger{0}){green}: %msg%n"
    file: "%d{HH:mm:ss.SSS} | %level | %logger{0}: %msg%n"
bookommerce:
  urls:
    web-base-url: https://app.bookommerce.com:8080
    api-gateway-base-url: https://bff.bookommerce.com:8181
    auth-server-base-url: https://auth.bookommerce.com:8282